Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -21,9 +21,10 @@ jobs:
           key: ${{ secrets.VPS_SSH_KEY }}
           script: |
             echo "Deploying NestJS app..."
-            cd ~/office_work/aaonisa-backend || exit 1
+            cd ~/office_work/AAONISA-BACKEND || exit 1
             git pull origin main || { echo 'Git pull failed'; exit 1; }
             npm install || { echo 'npm install failed'; exit 1; }
             npm run build || { echo 'Build failed'; exit 1; }
-            pm2 restart aaonisa-backend || { echo 'PM2 restart failed'; exit 1; }
+            pm2 restart backend || { echo 'PM2 restart failed'; exit 1; }
             echo "Deployment finished successfully ✅"
+            
